const allErrors = "ALL_ERRORS";
const SET_CURRENT_USER = "SETCURRENTUSER";
const SET_PROFILE = "SETPROFILE";
const SET_LOADER = "SETLOADER";
const SET_PROFILES = "SETPROFILES";
const SET_POSTS = "SETPOSTS";
const SET_POST = "SETPOST";

export {
  allErrors,
  SET_CURRENT_USER,
  SET_PROFILE,
  SET_LOADER,
  SET_PROFILES,
  SET_POSTS,
  SET_POST
};
